import { useEffect, useState } from 'react';
import { login, getProjects, createProject, deleteProject, getMessages } from '../services/api';

export default function Admin(){const [token,setToken]=useState(localStorage.getItem('adminToken'));const [loginForm,setLoginForm]=useState({email:'',password:''});const [projects,setProjects]=useState([]);const [messages,setMessages]=useState([]);const [form,setForm]=useState({title:'',description:'',technologies:'',githubUrl:'',liveUrl:'',featured:false});const [status,setStatus]=useState('');
async function load(){if(!token)return;try{setProjects(await getProjects());setMessages(await getMessages(token));}catch(e){setStatus(e.message)}}
useEffect(()=>{load()},[token]);
async function signIn(e){e.preventDefault();try{const r=await login(loginForm);localStorage.setItem('adminToken',r.token);setToken(r.token)}catch(e){setStatus(e.message)}}
async function add(e){e.preventDefault();try{await createProject({...form,technologies:form.technologies.split(',').map(x=>x.trim()).filter(Boolean)},token);setForm({title:'',description:'',technologies:'',githubUrl:'',liveUrl:'',featured:false});setStatus('Project added');load()}catch(e){setStatus(e.message)}}
async function remove(id){if(!confirm('Delete this project?'))return;await deleteProject(id,token);load()}
if(!token)return <div className="admin-page"><form className="admin-box" onSubmit={signIn}><h1>Admin Login</h1><input required type="email" placeholder="Email" value={loginForm.email} onChange={e=>setLoginForm({...loginForm,email:e.target.value})}/><input required type="password" placeholder="Password" value={loginForm.password} onChange={e=>setLoginForm({...loginForm,password:e.target.value})}/><button className="btn primary">Login</button><small>{status}</small></form></div>;
return <div className="admin-page"><div className="admin-head"><h1>Portfolio Admin</h1><button className="btn" onClick={()=>{localStorage.removeItem('adminToken');setToken(null)}}>Logout</button></div><div className="admin-grid"><form className="admin-box" onSubmit={add}><h2>Add Project</h2><input required placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Technologies: React, Node.js" value={form.technologies} onChange={e=>setForm({...form,technologies:e.target.value})}/><input placeholder="GitHub URL" value={form.githubUrl} onChange={e=>setForm({...form,githubUrl:e.target.value})}/><input placeholder="Live URL" value={form.liveUrl} onChange={e=>setForm({...form,liveUrl:e.target.value})}/><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><button className="btn primary">Add Project</button><small>{status}</small></form><div className="admin-box"><h2>Projects</h2>{projects.map(p=><div className="admin-item" key={p._id}><span><b>{p.title}</b><small>{(p.technologies||[]).join(', ')}</small></span><button onClick={()=>remove(p._id)}>Delete</button></div>)}</div><div className="admin-box"><h2>Messages</h2>{messages.length?messages.map(m=><div className="message" key={m._id}><b>{m.name}</b> · {m.email}<small>{new Date(m.createdAt).toLocaleString()}</small><p>{m.message}</p></div>):<p className="muted">No messages yet.</p>}</div></div></div>}
