import { useEffect, useState } from 'react';
import SectionTitle from '../components/SectionTitle';
import ProjectCard from '../components/ProjectCard';
import { getProjects,getSkills,sendMessage } from '../services/api';

const fallbackProjects=[{title:'Phishing Email Detection Model',description:'Machine-learning application that classifies email text as phishing or safe.',technologies:['Python','Scikit-learn','NLP'],githubUrl:'https://github.com/Hadesrules4/Phishing-Email-Detection-Model',featured:true},{title:'Password Strength Analyzer',description:'Security utility for evaluating password strength and common weakness patterns.',technologies:['Python','Cybersecurity','Regex'],githubUrl:'https://github.com/Hadesrules4/Password-Strength-Analyzer',featured:true},{title:'Vulnerability Scanner',description:'Educational defensive scanner for checking common network ports and generating a report.',technologies:['Python','Networking','Cybersecurity'],githubUrl:'https://github.com/Hadesrules4/Vulnerability-Scanner'}];

export default function Home(){const [projects,setProjects]=useState(fallbackProjects),[skills,setSkills]=useState([]),[filter,setFilter]=useState('All'),[form,setForm]=useState({name:'',email:'',message:''}),[status,setStatus]=useState('');
useEffect(()=>{getProjects().then(setProjects).catch(()=>{});getSkills().then(setSkills).catch(()=>{})},[]);
const categories=['All',...new Set(skills.map(s=>s.category))];const visible=filter==='All'?skills:skills.filter(s=>s.category===filter);
async function submit(e){e.preventDefault();try{await sendMessage(form);setForm({name:'',email:'',message:''});setStatus('Message sent successfully.');}catch(e){setStatus(e.message)}}
return <>
<section className="hero"><div><p className="eyebrow">B.Tech CSE / AI • Developer • Cybersecurity</p><h1>Building useful <span>digital experiences.</span></h1><p className="lead">I build full-stack applications, AI/ML projects and cybersecurity tools with a focus on practical problem solving.</p><div className="actions"><a className="btn primary" href="#projects">View Projects</a><a className="btn" href="#contact">Contact Me</a></div></div><div className="hero-card"><div className="avatar">PK</div><h2>Pranjal Kaushik</h2><p>Full-Stack & AI Enthusiast</p><div className="mini-grid"><span>React</span><span>Node.js</span><span>Python</span><span>MongoDB</span></div></div></section>
<section id="about"><SectionTitle eyebrow="01 — About" title="A little about me"/><div className="about-grid"><div><p>I am a B.Tech Computer Science / AI student interested in software engineering, machine learning and cybersecurity. This portfolio is designed as a complete full-stack project demonstrating frontend, backend, database and deployment integration.</p><p>I enjoy turning ideas into working applications and learning through hands-on projects.</p></div><div className="facts"><div><strong>3+</strong><span>Security projects</span></div><div><strong>AI/ML</strong><span>Learning & projects</span></div><div><strong>Full-Stack</strong><span>Web development</span></div></div></div></section>
<section id="skills"><SectionTitle eyebrow="02 — Skills" title="Tools I work with"/>{skills.length>0&&<div className="filter-row">{categories.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div>}<div className="skills-grid">{(visible.length?visible:[]).map(s=><div className="skill" key={s._id||s.name}><div><span>{s.name}</span><span>{s.level}%</span></div><div className="bar"><i style={{width:s.level+'%'}}/></div></div>)}</div></section>
<section id="projects"><SectionTitle eyebrow="03 — Projects" title="Selected work"/><div className="projects-grid">{projects.map((p,i)=><ProjectCard key={p._id||i} project={p}/>)}</div></section>
<section id="contact"><SectionTitle eyebrow="04 — Contact" title="Let's connect"/><div className="contact-grid"><div><p>Have a project idea, internship opportunity or technical question? Send a message.</p><div className="contact-list"><a href="https://github.com/Hadesrules4" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><form onSubmit={submit}><input required placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><textarea required rows="6" placeholder="Your message" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button className="btn primary">Send Message</button><small>{status}</small></form></div></section>
</>}
